image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install hexo-deployer-git --save
  - npm install
  - export HEXO_ALGOLIA_INDEXING_KEY=2cde5cb450401b66961edbc247dfda4d
  - hexo clean
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master