language: node_js
sudo: false
node_js:
  - '7'
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_ff8a8a056a0c_key -iv $encrypted_ff8a8a056a0c_iv
    -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name 'jingjiu'
  - git config --global user.email li949895691@163.com
install:
  - npm install hexo-cli -g
  - npm install hexo-deployer-git --save
  - npm install
  - export HEXO_ALGOLIA_INDEXING_KEY=2cde5cb450401b66961edbc247dfda4d
script:
  - hexo clean
  # - hexo algolia
  - hexo g -d
